"use client";

import { useMemo, useState } from "react";
import { Sidebar } from "@/components/Sidebar";
import { formatAud } from "@/lib/utils";
import { useFetch, LoadingState, ErrorState } from "@/lib/useFetch";
import type { Owner, Property } from "@/lib/types";
import { FileText, Download, Send } from "lucide-react";

type DataResponse = {
  properties: Property[];
  owners: Owner[];
};

const CERT_TYPES = [
  {
    id: "wa-6.76",
    label: "WA s.6.76 Rates Certificate",
    description: "Outstanding rates certificate for property settlement (WA Local Government Act 1995, s.6.76).",
    state: "WA",
    fee: 88,
  },
  {
    id: "nsw-603",
    label: "NSW s.603 Rates Certificate",
    description: "NSW Local Government Act 1993, s.603 — rates and charges as at the date of issue.",
    state: "NSW",
    fee: 95,
  },
  {
    id: "qld-95",
    label: "QLD Rates Search Certificate",
    description: "QLD Local Government Regulation 2012, Chapter 4 rates search.",
    state: "QLD",
    fee: 110,
  },
];

export default function CertificatesPage() {
  const fetchState = useFetch<DataResponse>("/api/data");
  const [certType, setCertType] = useState(CERT_TYPES[0].id);
  const [assessmentNumber, setAssessmentNumber] = useState("");
  const [requesterName, setRequesterName] = useState("");
  const [requesterEmail, setRequesterEmail] = useState("");
  const [generated, setGenerated] = useState<string | null>(null);

  // Hooks must run unconditionally — compute property/owner before early returns.
  const data = fetchState.status === "ok" ? fetchState.data : null;

  const property = useMemo(
    () => data?.properties.find((p) => p.assessmentNumber === assessmentNumber),
    [data, assessmentNumber],
  );
  const owner = useMemo(
    () => (property && data ? data.owners.find((o) => property.ownerIds.includes(o.ownerId)) : undefined),
    [property, data],
  );
  const certDef = CERT_TYPES.find((c) => c.id === certType)!;

  function generate() {
    if (!property || !owner) return;
    const today = new Date().toISOString().slice(0, 10);
    const certId = `CERT-${property.assessmentNumber}-${today.replace(/-/g, "")}`;
    setGenerated(`
═══════════════════════════════════════════════════════════════════
                      RATES CERTIFICATE
                          ${certDef.label}
═══════════════════════════════════════════════════════════════════

Certificate ID:    ${certId}
Issued:            ${today}
Statutory basis:   ${certDef.description}

PROPERTY
  Assessment:      ${property.assessmentNumber}
  Address:         ${property.address}, ${property.suburb} ${property.postcode}
  State:           ${property.state}
  Land use:        ${property.landUse}
  Valuation:       ${formatAud(property.valuation)}

OWNER OF RECORD
  Name:            ${owner.name}${owner.abn ? ` (ABN ${owner.abn})` : ""}
  Postal:          ${owner.postalAddress}
  Owner since:     ${owner.ownerSince}

RATES STATUS AS AT ${today}
  Annual rates:    ${formatAud(property.annualRates)}
  Outstanding:     ${formatAud(property.balance)}
  Last payment:    ${property.lastPaymentDate ?? "—"}${property.lastPaymentAmount ? ` (${formatAud(property.lastPaymentAmount)})` : ""}
  Payment plan:    ${property.paymentArrangement ? "Active" : "None"}
  Pensioner rebate:${property.pensionerRebate ? " Active" : " None"}

REQUESTED BY
  Name:            ${requesterName || "[not specified]"}
  Email:           ${requesterEmail || "[not specified]"}

FEE
  Certificate fee: ${formatAud(certDef.fee)} (paid via Stripe / counter)

DECLARATION
  This certificate is issued under the cited statutory provision.
  Rates outstanding at the date of issue are as shown. Any liability
  for rates accruing after the date of issue is not affected by this
  certificate. Adjustments arising from supplementary valuations, owner
  changes, or rate-setting decisions made after the date of issue may
  apply.

  Signed under delegation by the Chief Executive Officer.

═══════════════════════════════════════════════════════════════════
        Generated by RatesAssist · ${certId} · Confidential
═══════════════════════════════════════════════════════════════════
`.trim());
  }

  if (fetchState.status === "loading") return <LoadingState />;
  if (fetchState.status === "error") return <ErrorState message={fetchState.error} />;

  return (
    <div className="flex h-screen">
      <Sidebar />
      <main className="flex-1 flex flex-col overflow-hidden">
        <div className="px-6 py-4 border-b border-ink-200 bg-white">
          <h1 className="text-xl font-semibold text-ink-900 flex items-center gap-2">
            <FileText className="w-5 h-5 text-accent-500" />
            Rates Certificates
          </h1>
          <div className="text-sm text-ink-500">
            Statutory rates certificates for property settlement, conveyancing, and
            third-party requests.
          </div>
        </div>

        <div className="flex-1 overflow-hidden flex">
          <div className="w-[440px] border-r border-ink-200 bg-white p-5 overflow-y-auto space-y-5">
            <div>
              <label className="label mb-1 block">Certificate type</label>
              <select
                className="input"
                value={certType}
                onChange={(e) => setCertType(e.target.value)}
              >
                {CERT_TYPES.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.label} — {formatAud(c.fee)}
                  </option>
                ))}
              </select>
              <div className="text-xs text-ink-500 mt-1">{certDef.description}</div>
            </div>

            <div>
              <label className="label mb-1 block">Assessment number</label>
              <input
                className="input"
                placeholder="e.g. TPS-1102-44"
                value={assessmentNumber}
                onChange={(e) => setAssessmentNumber(e.target.value.toUpperCase())}
              />
              {data && assessmentNumber && (
                <div className="text-xs mt-1">
                  {property ? (
                    <span className="text-success-700">
                      ✓ {property.address}, {property.suburb}
                    </span>
                  ) : (
                    <span className="text-warn-700">No property found</span>
                  )}
                </div>
              )}
            </div>

            <div>
              <label className="label mb-1 block">Requester name</label>
              <input
                className="input"
                placeholder="e.g. Henderson Lawyers"
                value={requesterName}
                onChange={(e) => setRequesterName(e.target.value)}
              />
            </div>

            <div>
              <label className="label mb-1 block">Requester email</label>
              <input
                className="input"
                type="email"
                placeholder="conveyancer@example.com"
                value={requesterEmail}
                onChange={(e) => setRequesterEmail(e.target.value)}
              />
            </div>

            <button
              className="btn-primary w-full"
              disabled={!property}
              onClick={generate}
            >
              <FileText className="w-4 h-4" />
              Generate certificate
            </button>

            {generated && (
              <div className="space-y-2 pt-3 border-t border-ink-200">
                <button
                  className="btn-ghost w-full border border-ink-200"
                  onClick={() => {
                    const blob = new Blob([generated], { type: "text/plain" });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement("a");
                    a.href = url;
                    a.download = `cert-${assessmentNumber}.txt`;
                    a.click();
                    URL.revokeObjectURL(url);
                  }}
                >
                  <Download className="w-4 h-4" />
                  Download
                </button>
                <button
                  className="btn-ghost w-full border border-ink-200"
                  disabled={!requesterEmail}
                >
                  <Send className="w-4 h-4" />
                  Email to requester
                </button>
              </div>
            )}

            {property && (
              <div className="card p-4 bg-ink-50 border-ink-200">
                <div className="label mb-2">Property summary</div>
                <div className="text-sm space-y-1">
                  <div>
                    <span className="text-ink-500">Address:</span>{" "}
                    <span className="font-medium">{property.address}</span>
                  </div>
                  <div>
                    <span className="text-ink-500">Land use:</span>{" "}
                    {property.landUse}
                  </div>
                  <div>
                    <span className="text-ink-500">Annual rates:</span>{" "}
                    {formatAud(property.annualRates)}
                  </div>
                  <div>
                    <span className="text-ink-500">Outstanding:</span>{" "}
                    <span className={property.balance > 0 ? "text-warn-700 font-medium" : ""}>
                      {formatAud(property.balance)}
                    </span>
                  </div>
                </div>
              </div>
            )}
          </div>

          <div className="flex-1 bg-ink-50 p-6 overflow-y-auto">
            {generated ? (
              <pre className="card p-6 font-mono text-xs leading-relaxed whitespace-pre-wrap text-ink-800">
                {generated}
              </pre>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-ink-400 text-sm">
                <FileText className="w-12 h-12 mb-3 text-ink-300" />
                Configure the certificate, then click <strong className="mx-1">Generate</strong>{" "}
                to produce a council-grade artefact.
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
